config/routes.rb
IguassuPass::Application.routes.draw do
  resources :homes

  resources :usuarios

  resources :atracaos

   match ':controller(/:action(/:id))(.:format)'
end

app/models/atracao.rb
class Atracao < ActiveRecord::Base
  attr_accessible :custo, :nome
end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :Bairro, :CEP, :CPF, :Cidade, :Complemento, :Email, :First, :Last, :Name, :Name, :Numero, :Pais, :RuaAv, :Telefone, :UF
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/atracaos_controller.rb
class AtracaosController < ApplicationController
  # GET /atracaos
  # GET /atracaos.json
  def index
    @atracaos = Atracao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @atracaos }
    end
  end

  # GET /atracaos/1
  # GET /atracaos/1.json
  def show
    @atracao = Atracao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @atracao }
    end
  end

  # GET /atracaos/new
  # GET /atracaos/new.json
  def new
    @atracao = Atracao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @atracao }
    end
  end

  # GET /atracaos/1/edit
  def edit
    @atracao = Atracao.find(params[:id])
  end

  # POST /atracaos
  # POST /atracaos.json
  def create
    @atracao = Atracao.new(params[:atracao])

    respond_to do |format|
      if @atracao.save
        format.html { redirect_to @atracao, :notice => 'Atracao was successfully created.' }
        format.json { render :json => @atracao, :status => :created, :location => @atracao }
      else
        format.html { render :action => "new" }
        format.json { render :json => @atracao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /atracaos/1
  # PUT /atracaos/1.json
  def update
    @atracao = Atracao.find(params[:id])

    respond_to do |format|
      if @atracao.update_attributes(params[:atracao])
        format.html { redirect_to @atracao, :notice => 'Atracao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @atracao.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /atracaos/1
  # DELETE /atracaos/1.json
  def destroy
    @atracao = Atracao.find(params[:id])
    @atracao.destroy

    respond_to do |format|
      format.html { redirect_to atracaos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, :notice => 'Home was successfully created.' }
        format.json { render :json => @home, :status => :created, :location => @home }
      else
        format.html { render :action => "new" }
        format.json { render :json => @home.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, :notice => 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @home.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, :notice => 'Usuario was successfully created.' }
        format.json { render :json => @usuario, :status => :created, :location => @usuario }
      else
        format.html { render :action => "new" }
        format.json { render :json => @usuario.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, :notice => 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @usuario.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atracaos_helper.rb
module AtracaosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/atracao/_form.html.erb
<%= form_for @atracao, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :custo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :custo, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                atracao_path, :class => 'btn' %>
  </div>
<% end %>

app/views/atracao/edit.html.erb
<%- model_class = Atracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/atracao/index.html.erb
<%- model_class = Atracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:custo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @atracaos.each do |atracao| %>
      <tr>
        <td><%= link_to atracao.id, atracao_path(atracao) %></td>
        <td><%= atracao.nome %></td>
        <td><%= atracao.custo %></td>
        <td><%=l atracao.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_atracao_path(atracao), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      atracao_path(atracao),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_atracao_path,
            :class => 'btn btn-primary' %>

app/views/atracao/new.html.erb
<%- model_class = Atracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/atracao/show.html.erb
<%- model_class = Atracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @atracao.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:custo) %>:</strong></dt>
  <dd><%= @atracao.custo %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              atracao_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_atracao_path(@atracao), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              atracao_path(@atracao),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/atracaos/_form.html.erb
<%= form_for @atracao, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :custo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :custo, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                atracaos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/atracaos/edit.html.erb
<%- model_class = Atracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/atracaos/index.html.erb
<%- model_class = Atracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:custo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @atracaos.each do |atracao| %>
      <tr>
        <td><%= link_to atracao.id, atracao_path(atracao) %></td>
        <td><%= atracao.nome %></td>
        <td><%= atracao.custo %></td>
        <td><%=l atracao.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_atracao_path(atracao), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      atracao_path(atracao),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_atracao_path,
            :class => 'btn btn-primary' %>

app/views/atracaos/new.html.erb
<%- model_class = Atracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/atracaos/show.html.erb
<%- model_class = Atracao -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @atracao.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:custo) %>:</strong></dt>
  <dd><%= @atracao.custo %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              atracaos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_atracao_path(@atracao), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              atracao_path(@atracao),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IguassuPass" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">IguassuPass</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Usuario", "/path1"  %></li>
              <li><%= link_to "Locais", "/path2"  %></li>
              <li><%= link_to "Atrações", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Menu</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Fotos</li>
                  <li><%= link_to "Itaipu", "/path1"  %></li>
                  <li><%= link_to "Cataratas", "/path2"  %></li>
                  <li><%= link_to "Parque das Aves", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/usuario/_form.html.erb
<%= form_for @usuario, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :First, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :First, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Last, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Last, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :CPF, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :CPF, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Telefone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Telefone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :CEP, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :CEP, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :RuaAv, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :RuaAv, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Numero, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Numero, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Complemento, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Complemento, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Bairro, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Bairro, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Cidade, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Cidade, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :UF, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :UF, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Pais, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :Pais, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                usuario_path, :class => 'btn' %>
  </div>
<% end %>

app/views/usuario/edit.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/usuario/index.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:First) %></th>
      <th><%= model_class.human_attribute_name(:Name) %></th>
      <th><%= model_class.human_attribute_name(:Last) %></th>
      <th><%= model_class.human_attribute_name(:Email) %></th>
      <th><%= model_class.human_attribute_name(:CPF) %></th>
      <th><%= model_class.human_attribute_name(:Telefone) %></th>
      <th><%= model_class.human_attribute_name(:CEP) %></th>
      <th><%= model_class.human_attribute_name(:RuaAv) %></th>
      <th><%= model_class.human_attribute_name(:Numero) %></th>
      <th><%= model_class.human_attribute_name(:Complemento) %></th>
      <th><%= model_class.human_attribute_name(:Bairro) %></th>
      <th><%= model_class.human_attribute_name(:Cidade) %></th>
      <th><%= model_class.human_attribute_name(:UF) %></th>
      <th><%= model_class.human_attribute_name(:Pais) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.id, usuario_path(usuario) %></td>
        <td><%= usuario.First %></td>
        <td><%= usuario.Name %></td>
        <td><%= usuario.Last %></td>
        <td><%= usuario.Email %></td>
        <td><%= usuario.CPF %></td>
        <td><%= usuario.Telefone %></td>
        <td><%= usuario.CEP %></td>
        <td><%= usuario.RuaAv %></td>
        <td><%= usuario.Numero %></td>
        <td><%= usuario.Complemento %></td>
        <td><%= usuario.Bairro %></td>
        <td><%= usuario.Cidade %></td>
        <td><%= usuario.UF %></td>
        <td><%= usuario.Pais %></td>
        <td><%=l usuario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_usuario_path(usuario), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      usuario_path(usuario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_usuario_path,
            :class => 'btn btn-primary' %>

app/views/usuarios/index.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:First) %></th>
      <th><%= model_class.human_attribute_name(:Name) %></th>
      <th><%= model_class.human_attribute_name(:Last) %></th>
      <th><%= model_class.human_attribute_name(:Email) %></th>
      <th><%= model_class.human_attribute_name(:CPF) %></th>
      <th><%= model_class.human_attribute_name(:Telefone) %></th>
      <th><%= model_class.human_attribute_name(:CEP) %></th>
      <th><%= model_class.human_attribute_name(:RuaAv) %></th>
      <th><%= model_class.human_attribute_name(:Numero) %></th>
      <th><%= model_class.human_attribute_name(:Complemento) %></th>
      <th><%= model_class.human_attribute_name(:Bairro) %></th>
      <th><%= model_class.human_attribute_name(:Cidade) %></th>
      <th><%= model_class.human_attribute_name(:UF) %></th>
      <th><%= model_class.human_attribute_name(:Pais) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= link_to usuario.id, usuario_path(usuario) %></td>
        <td><%= usuario.First %></td>
        <td><%= usuario.Name %></td>
        <td><%= usuario.Last %></td>
        <td><%= usuario.Email %></td>
        <td><%= usuario.CPF %></td>
        <td><%= usuario.Telefone %></td>
        <td><%= usuario.CEP %></td>
        <td><%= usuario.RuaAv %></td>
        <td><%= usuario.Numero %></td>
        <td><%= usuario.Complemento %></td>
        <td><%= usuario.Bairro %></td>
        <td><%= usuario.Cidade %></td>
        <td><%= usuario.UF %></td>
        <td><%= usuario.Pais %></td>
        <td><%=l usuario.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_usuario_path(usuario), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      usuario_path(usuario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_usuario_path,
            :class => 'btn btn-primary' %>